# Generated by Django 4.1 on 2023-11-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save_movie',
            name='name',
        ),
    ]
