# Generated by Django 4.1 on 2023-11-16 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_remove_save_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='save_movie',
            name='ids',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='save_movie',
            name='name',
            field=models.CharField(default='aman', max_length=500),
        ),
        migrations.AddField(
            model_name='save_movie',
            name='usr',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
