# Generated by Django 4.1 on 2023-11-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_save_movie_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save_movie',
            name='ids',
        ),
        migrations.AddField(
            model_name='save_movie',
            name='movie_id',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
