# Generated by Django 4.1 on 2023-11-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_save_movie_ids_save_movie_movie_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='save_movie',
            old_name='usr',
            new_name='usr_name',
        ),
    ]
