# Generated by Django 4.1 on 2023-11-16 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_rename_usr_save_movie_usr_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save_movie',
            name='usr_name',
            field=models.ForeignKey(default='free', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
