# Generated by Django 4.1 on 2023-11-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_savedmovie_remove_userprofile_saved_movies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmovie',
            name='movieid',
            field=models.CharField(max_length=100, null='false'),
            preserve_default='false',
        ),
    ]
