# Generated by Django 4.1 on 2023-11-16 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_alter_savedmovie_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedmovie',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='savedmovie',
            name='movieid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='savedmovie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
