# Generated by Django 4.1 on 2023-11-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_savedmovie_id_alter_savedmovie_movieid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedmovie',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
