# Generated by Django 4.1 on 2023-11-16 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_savedmovie_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedMovie',
        ),
    ]
