# Generated by Django 4.1 on 2023-11-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0003_remove_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='moviesave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('ids', models.CharField(max_length=100)),
            ],
        ),
    ]
