# Generated by Django 4.1 on 2023-11-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0004_moviesave'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesave',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
