# Generated by Django 4.1 on 2023-11-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0005_moviesave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesave',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
