# Generated by Django 4.1 on 2023-11-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0006_moviesave_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesave',
            name='overview',
            field=models.TextField(null=True),
        ),
    ]
